name: Trigger auto deployment for container-app-msxjm555schzk

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-msxjm555schzk-AutoDeployTrigger-c5ad17f3-0e45-4730-8fc6-09bccde80a44.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPMSXJM555SCHZK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPMSXJM555SCHZK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPMSXJM555SCHZK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPMSXJM555SCHZK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPMSXJM555SCHZK_REGISTRY_PASSWORD }}
          containerAppName: container-app-msxjm555schzk
          resourceGroup: test-RAG
          imageToBuild: default/container-app-msxjm555schzk:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


