name: Trigger auto deployment for container-app-szjikyx55dv4m

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-szjikyx55dv4m-AutoDeployTrigger-c170c3ae-f019-4c3f-9ca9-ac424204959c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPSZJIKYX55DV4M_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPSZJIKYX55DV4M_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPSZJIKYX55DV4M_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPSZJIKYX55DV4M_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPSZJIKYX55DV4M_REGISTRY_PASSWORD }}
          containerAppName: container-app-szjikyx55dv4m
          resourceGroup: appspacesragapp83079734
          imageToBuild: default/container-app-szjikyx55dv4m:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


